language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
before_deploy:
  - wget "https://gist.githubusercontent.com/fennifith/4221a79ec5f39c21085fec4c41d7d160/raw/bintray.json"
  - wget "https://gist.githubusercontent.com/fennifith/4221a79ec5f39c21085fec4c41d7d160/raw/gen-bintray-descriptor.sh" -o ./.scripts/gen-bintray-desc.sh
  - chmod +x .scripts/gen-bintray-desc.sh && ./.scripts/gen-bintray-desc.sh
deploy:
  provider: bintray
  skip_cleanup: true
  file: "bintray.json"
  user: "18jafenn90"
  key: $BINTRAY_KEY
  on:
      all_branches: true