language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_88ddc75bcd79_key -iv $encrypted_88ddc75bcd79_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar --overwrite
  - chmod +x gradlew
script:
  - ./gradlew build
before_deploy:
  - chmod +x .scripts/gen-bintray-descriptor.sh
  - .scripts/gen-bintray-descriptor.sh
deploy:
  provider: bintray
  skip_cleanup: true
  file: "bintray.json"
  user: "18jafenn90"
  key: $BINTRAY_KEY
  on:
      all_branches: true
